services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  # Postgres database service.
  # Since the data is just for testing purpose, we don't persist it to a volume.
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
