// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Numpool represents an abstract pool of resources.
type Numpool struct {
	// ID is a unique identifier for the numpool.
	// It is used to identify the numpool in the database.
	ID string
	// MaxResourcesCount is the maximum number of resources that can be allocated.
	// It is used to limit the number of resources that can be created.
	// The value must be between 1 and 64, inclusive.
	MaxResourcesCount int32
	// ResourceUsageStatus is a bitmask representing the usage of resources.
	// Each bit corresponds to a resource, where 1 means the resource is in use and 0 means it is free.
	// The length of the bitmask is equal to MaxResourcesCount.
	// For example, if MaxResourcesCount is 8, then ResourceUsageStatus can be a value from 0 to 64, where each bit represents the usage of a resource.
	ResourceUsageStatus pgtype.Bits
	// WaitQueue is a list of client ids waiting for the numpool.
	WaitQueue []string
	// Metadata is a JSONB field that can store additional information about the numpool.
	// It can be used to store any additional data that is relevant to the numpool, such as
	// configuration settings, descriptions, or other metadata that does not fit into the other fields.
	Metadata []byte
}
